<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="base_length" value="0.41" />
    <xacro:property name="base_width" value="0.32" />
    <xacro:property name="base_height" value="0.15" />
    <xacro:property name="pillar_length" value="0.05" />
    <xacro:property name="pillar_width" value="0.02" />
    <xacro:property name="pillar_height" value="0.56" />
    <xacro:property name="wheel_radius" value="0.075" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="platform_length" value="0.16" />
    <xacro:property name="platform_width" value="0.21" />
    <xacro:property name="platform_height" value="0.14" />

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>
    
    <xacro:macro name="pillar_link" params="prefix">
        <link name="${prefix}_pillar_link">
            <visual>
                <geometry>
                    <box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
                </geometry>
                <origin xyz="0 0 ${pillar_height / 2.0}" rpy="0 0 0" />
                <material name="black"/>
            </visual>
                <collision>
                    <geometry>
                        <box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
                    </geometry>
                    <origin xyz="0 0 ${pillar_height / 2.0}" rpy="0 0 0" />
                </collision>
            <xacro:box_inertia m="5.0" l="${2*pillar_length}" w="${2*pillar_width}" h="${2*pillar_height}"
                            xyz="0 0 ${pillar_height / 2.0}" rpy="0 0 0"/>
        </link>
    </xacro:macro>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue"/>
        </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
    </link>

    <link name="upper_platform_link">
        <visual>
            <geometry>
                <box size="${platform_length} ${platform_width} ${platform_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue"/>
        </visual>
            <collision>
                <geometry>
                    <box size="${platform_length} ${platform_width} ${platform_height}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
        <xacro:box_inertia m="5.0" l="${2*platform_length}" w="${2*platform_width}" h="${2*platform_height}"
                           xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <xacro:wheel_link prefix="rr"/>
    <xacro:wheel_link prefix="rl"/>
    <xacro:wheel_link prefix="fr"/>
    <xacro:wheel_link prefix="fl"/>
    <xacro:pillar_link prefix="right_front"/>
    <xacro:pillar_link prefix="left_front"/>
    <xacro:pillar_link prefix="right_rear"/>
    <xacro:pillar_link prefix="left_rear"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.03" rpy="0 0 0"/>
    </joint>

    <joint name="upper_platform_joint" type="fixed">
        <parent link="base_link"/>
        <child link="upper_platform_link"/>
        <origin xyz="0 0 ${pillar_height + base_height +0.14 / 2.0}" rpy="0 0 0"/>
    </joint>
    
    <joint name="rr_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rr_wheel_link"/>
        <origin xyz="${-base_length / 2.0} ${-(base_width + wheel_length) / 2.0} 0.045" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="rl_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rl_wheel_link"/>
        <origin xyz="${-base_length / 2.0} ${(base_width + wheel_length) / 2.0} 0.045" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    <joint name="fr_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="fr_wheel_link"/>
        <origin xyz="${base_length / 2.0} ${-(base_width + wheel_length) / 2.0} 0.045" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="fl_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="fl_wheel_link"/>
        <origin xyz="${base_length / 2.0} ${(base_width + wheel_length) / 2.0} 0.045" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="right_front_pillar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_front_pillar_link"/>
        <origin xyz="0.05 0.07 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="left_front_pillar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_front_pillar_link"/>
        <origin xyz="0.05 -0.07 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    <joint name="right_rear_pillar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_rear_pillar_link"/>
        <origin xyz="-0.05 0.07 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="left_rear_pillar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_rear_pillar_link"/>
        <origin xyz="-0.05 -0.07 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

</robot>
